title: Zuhri Utama Homepage
page-top-title: Zuhri Utama
top-section-bg-text: Zuhri Utama&ensp;|&ensp;IDempiere Core Team
home-subtitle: My Background
copyright-text: '&copy; Zuhri Utama 2025. All Rights Reserved.'
