title: Zuhri Utama Homepage
page-top-title: Zuhri Utama
top-section-bg-text: Welcome to my homepage
home-subtitle: Zuhri Utama&ensp;|&ensp;IDempiere Core Team
copyright-text: '&copy; Zuhri Utama 2025. All Rights Reserved.'
